FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD mlflow ui \
    --backend-store-uri sqlite:////app/mlflow/mlflow.db \
    --default-artifact-root /app/mlflow/artifacts \
    --host 0.0.0.0 --port 5000
